# Generated by Django 2.1.5 on 2019-07-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paDB', '0003_auto_20190703_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdiscussion',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paDB.Report'),
            preserve_default=False,
        ),
    ]
